[Interface]
Address = 10.99.99.1/24
ListenPort = 51820
PrivateKey = YEfbaTydyE65Q3sv7jyUDGk4E+I20zjYab8eiFQSo3k=

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o enp0s3 -j MASQUERADE

[Peer]
PublicKey = bhE4UcSPxObNch3DmC1lXVHvWwrUWoKNszwE0sOo7WE=
AllowedIPs = 10.99.99.2/32
