network:
  version: 2
  ethernets:
    enp0s3:
      addresses:
        - 10.20.20.10/24
      routes:
        - to: default
          via: 10.20.20.1
      nameservers:
        addresses: [10.20.20.1]
        search: [dmz.millornet.local]

    enp0s8:
      addresses:
        - 192.168.56.103/24
