network:
  version: 2
  ethernets:
    enp0s3:
      addresses:
        - 10.10.10.10/24
      routes:
        - to: default
          via: 10.10.10.1
      nameservers:
        addresses: [10.10.10.1]
        search: [millornet.local]

    enp0s8:
      addresses:
        - 192.168.56.102/24
