version: '3.8'

services:

  dvwa:
    image: vulnerables/web-dvwa
    container_name: lab-dvwa
    ports:
      - "8080:80"
    restart: unless-stopped

  webgoat:
    image: webgoat/webgoat
    container_name: lab-webgoat
    ports:
      - "8081:8080"
    restart: unless-stopped

  juiceshop:
    image: bkimminich/juice-shop
    container_name: lab-juiceshop
    ports:
      - "8082:3000"
    restart: unless-stopped
  mutillidae:
    image: citizenstig/nowasp
    container_name: lab-mutillidae
    ports:
      - "8083:80"
    restart: unless-stopped
