tls:
  certificates:
    - certFile: /certs/millornet-server.crt
      keyFile: /certs/millornet-server.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/millornet-server.crt
        keyFile: /certs/millornet-server.key
